config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#Rutas paera manipular las solicitudes
  #

get '/inicio' => 'solicitudes#index'
get '/solicitud/:id' => 'solicitudes#show',as: :verSolicitud
get '/new/solicitud'  => 'solicitudes#new'
post 'new/solicitud' =>'solicitudes#create'
get '/solicitud/:id' => 'solicitudes#show',as: :showSolicitud
get '/solicitud/admin/:id' => 'solicitudes#showAdmin',as: :showSolicitudAdmin
patch '/solicitud/admin/:id' =>'solicitudes#updateEstatus', as: :updateEstatus


#Rutas para manipular usuario
  # **************************
get '/users' => 'usuarios#index'
get '/new/usuario' => 'usuarios#new'
get '/usuario/:id/ver' => 'usuarios#ver', as: :showUser
post '/new/usuario' => 'usuarios#create'
get 'usuario/:id/edit' => 'usuarios#edit', as: :edit
patch 'usuario/:id' => 'usuarios#update', as: :update
get 'usuario/:id/show' => 'usuarios#editar', as: :editar_ver

  #Rutas para manipular session
  # ***************************
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
delete '/logout' => 'sessions#destroy'

#Rutas para manipularr Acceso Rapido
   get '/accesos' => 'accesos#index'
  get '/new/acceso' => 'accesos#new'
  post  '/new/acceso' =>'accesos#create'
get '/acceso/:id' => 'accesos#show', as: :showAcceso
  get '/accesos/user' => 'accesos#indexUser', as: :accesosIndexUser
  get '/acceso/user/:id' => 'accesos#showUser',as: :showAccesoUser



#Rutas para las solicitudes de los usuarios

get '/user/inicio' => 'solicitudes#indexUser',as: :userInicio



root 'sessions#new'

end

app/models/acceso.rb
class Acceso < ApplicationRecord
  validates :Correo, presence: {message: 'No puede dejarse vacio'},email: {message:'Inavlido, Utilizar @/gmail/hotmail/labreferencia/.com, ejemplo: example@labreferencia.com'}
  validates :CodigoEmpleado,:Nombre,:Empresa, presence: {message:'No puede dejarse vacio'}
  validates :Companero, :Mensaje, presence: {message:'No puede dejarse vacio'}
  validates :Departamento,:Funcion,presence: {message:'No puede dejarse vacio'}

end

app/controllers/accesos_controller.rb
class AccesosController < ApplicationController
  def index
    @AccesosEmergente = Acceso.paginate(:page => params[:page], :per_page => 8)
  end

  def show
    @Acceso = Acceso.find(params[:id])
  end

  def showUser
    @Acceso = Acceso.find(params[:id])
  end




  def create
    @Acceso= Acceso.new(params_acceso)
    if @Acceso.save
      redirect_to '/login'
    else
  render 'sessions/new'
    end

  end

  def indexUser
    @AccesoUser= Acceso.where('CodigoEmpleado = ?',current_user.CodigoEmpleado).paginate(:page => params[:page], :per_page => 8)
  end






  private

  def params_acceso
    params.require(:acceso).permit(:Nombre,:Departamento,:Correo,:Funcion,:CodigoEmpleado,:Companero,:Mensaje,:Empresa,:Telefono)
  end


end

app/helpers/accesos_helper.rb
module AccesosHelper
end

app/views/accesos/index.html.erb
<header class="cabecera-principal">
  <div class="logo-princial">
    <%= image_tag 'logo.png', alt: 'Regerencia Data Center' %>
  </div>
  <div class="">

    <span><span><strong> Admin:</strong></span> <%= current_user.NombreCompleto %>.</span>
    <%= link_to "Cerrar session", logout_path, method: :delete, class: 'btn-custome btn-hollow-blue' %>

  </div>
</header>

<div class="cuerpo-principal">
  <aside class="menu">
    <div class="iconos estilo-menu">
      <ul>
        <li class="">
          <a href="inicio" class="hint--right" aria-label="Lista de solicitud"><span class="fa fa-address-book"></span></a>
        </li>
        <li class="">
          <a href="accesos" class="hint--right" aria-label="Lista de acceso emergente"><span class="fa fa-ambulance"></span></a>
        </li>
        <li class=""><a href="users" class="hint--right" aria-label="Usuario"><span class="fa fa-users"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Reportes"><span class="fa fa-file"></span></a></li>
        <li class="">
          <a href="" class="hint--right" aria-label="Estadisticas"><span class="fa fa-bar-chart-o"></span></a></li>
      </ul>
    </div>
    <div class="texto-iconos estilo-menu">
      <ul>
        <li class=""><%= link_to 'Lista de Solicitud', inicio_path %></li>
        <li class=""><%= link_to 'Lista de acceso emergente', accesos_path %></li>
        <li class=""><%= link_to 'Usuarios',users_path %></li>
        <li class=""><a href="#"> Reportes</a></li>
        <li class=""><a href="#"> Estadisticas</a></li>
      </ul>
    </div>
  </aside>

  <main class="contenido-principal ">
    <header class="contenido-titulo titulo-emergente">
      <h3 class="text-center"><span class="fa fa-ambulance"></span>Lista de acceso emergente</h3>
    </header>
    <section class="contenido-informacion">
      <div class="">
        <% if @AccesosEmergente.empty? %>
          <p style="text-align: center"> <strong> No hay datos para mostrar</strong> </p>
        <% else %>
          <table class="table-custome" summary="las solicitudes por usuario">
            <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Correo</th>
              <th>Fecha</th>
              <th>Hora/Entrada</th>
              <th>Acción</th>
            </tr>

            <thead>
            <tbody class="cuerpo-table">
            <% @AccesosEmergente.each do |s| %>
              <tr >
                <td><%=s.id %></td>
                <td><%=s.Nombre %></td>
                <td><%=s.Correo %></td>
                <td><%=s.created_at.strftime("%d/%B/%Y") %></td>
                <td><%=s.created_at.strftime("%I:%M:%S %p") %></td>

                <td><%=link_to 'Detalle', showAcceso_path(s)%></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </section>
    <footer class="controladores">
      <%= will_paginate @AccesosEmergente, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

    </footer>
  </main>

</div>

app/views/accesos/indexUser.html.erb
<header class="cabecera-principal">
  <div class="logo-princial">
    <%= image_tag 'logo.png', alt: 'Regerencia Data Center' %>
  </div>
  <div class="">

    <span><span><strong> Usuario:</strong></span> <%= current_user.NombreCompleto %>.</span>
    <%= link_to "Cerrar session", logout_path, method: :delete, class: 'btn-custome btn-hollow-blue' %>

  </div>
</header>
<div class="cuerpo-principal">
  <aside class="menu">
    <div class="iconos estilo-menu ">
      <ul>
        <li class=""><a href="" class="hint--right" aria-label="Lista de solicitud"><span class="fa fa-address-book"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Crear Solicitud"><span class="fa fa-address-book"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Lista de acceso emergente"><span class="fa fa-ambulance"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Visitas"><span class="fa fa-clipboard"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Editar usuario"><span class="fa fa-edit"></span></a></li>
      </ul>
    </div>
    <div class="texto-iconos estilo-menu">
      <ul>
        <li class=""><%= link_to 'Lista de Solicitud', userInicio_path %></li>
        <li class=""><%= link_to 'Crear de Solicitud', new_solicitud_path %></li>
        <li class=""><%= link_to 'Lista de acceso emergente', accesosIndexUser_path %></li>
        <li class=""><a href="#"> Visitas</a></li>
        <li class=""><a href="#"> Editar usuario</a></li>
      </ul>
    </div>
  </aside>

  <main class="contenido-principal ">
    <header class="contenido-titulo titulo-emergente">
      <h3 class="text-center"><span class="fa fa-ambulance"></span>Lista de acceso emergente</h3>
    </header>
    <section class="contenido-informacion">
      <div class="">
        <% if @AccesoUser.empty? %>
          <p style="text-align: center"> <strong> No hay datos para mostrar</strong> </p>
        <% else %>
          <table class="table-custome" summary="las solicitudes por usuario">
            <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Correo</th>
              <th>Fecha</th>
              <th>Hora/Entrada</th>
              <th>Acción</th>
            </tr>

            <thead>
            <tbody class="cuerpo-table">
            <% @AccesoUser.each do |s| %>
              <tr >
                <td><%=s.id %></td>
                <td><%=s.Nombre %></td>
                <td><%=s.Correo %></td>
                <td><%=s.created_at.strftime("%d/%B/%Y") %></td>
                <td><%=s.created_at.strftime("%I:%M:%S %p") %></td>

                <td><%=link_to 'Detalle', showAccesoUser_path(s)%></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </section>
    <footer class="controladores">
      <%= will_paginate @AccesoUser, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

    </footer>
  </main>

</div>

app/views/accesos/show.html.erb
<header class="cabecera-principal">
  <div class="logo-princial">
    <%= image_tag 'logo.png', alt: 'Regerencia Data Center' %>
  </div>
  <div class="">

    <span><span><strong> Admin:</strong></span> <%= current_user.NombreCompleto %>.</span>
    <%= link_to "Cerrar session", logout_path, method: :delete, class: 'btn-custome btn-hollow-blue' %>

  </div>
</header>

<div class="cuerpo-principal">
  <aside class="menu">
    <div class="iconos estilo-menu">
      <ul>
        <li class="">
          <a href="inicio" class="hint--right" aria-label="Lista de solicitud"><span class="fa fa-address-book"></span></a>
        </li>
        <li class="">
          <a href="accesos" class="hint--right" aria-label="Lista de acceso emergente"><span class="fa fa-ambulance"></span></a>
        </li>
        <li class=""><a href="users" class="hint--right" aria-label="Usuario"><span class="fa fa-users"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Reportes"><span class="fa fa-file"></span></a></li>
        <li class="">
          <a href="" class="hint--right" aria-label="Estadisticas"><span class="fa fa-bar-chart-o"></span></a></li>
      </ul>
    </div>
    <div class="texto-iconos estilo-menu">
      <ul>
        <li class=""><%= link_to 'Lista de Solicitud', inicio_path %></li>
        <li class=""><%= link_to 'Lista de acceso emergente', accesos_path %></li>
        <li class=""><%= link_to 'Usuarios', users_path %></li>
        <li class=""><a href="#"> Reportes</a></li>
        <li class=""><a href="#"> Estadisticas</a></li>
      </ul>
    </div>
  </aside>

  <main class="contenido-principal">
    <header class="contenido-titulo titulo-emergente">
      <h3 class="text-center"><span class="fa fa-ambulance"></span>Detalle acceso emergente</h3>
    </header>
    <section class=" contenido-user-crear " >
      <div class="cabecera-user-crear">
        <p><span>Id Solicitud:</span><%=@Acceso.id%></p>
        <p><span>Fecha:</span><%= @Acceso.created_at.strftime("%d/%B/%Y")   %></p>
      </div>




      <div class="datos-usuario">
        <h3>Datos del usuario</h3>
        <div>
          <div class="">
            <p><span>Usuario:</span> <%= @Acceso.Nombre %></p>
            <p><span>Codigo:</span> <%= @Acceso.CodigoEmpleado %></p>
            <p><span>Departamento:</span><%= @Acceso.Departamento %></p>


          </div>

          <div class="">
            <p><span>Correo:</span> <%= @Acceso.Correo %></p>
            <p><span>Función:</span> <%= @Acceso.Funcion %></p>
          </div>
        </div>
      </div>

      <div class="">
        <h3>Datos de la visita</h3>
        <div class="datos-vista">
          <div class="">

            <div class="row">
              <div class="col-md-6">
                <p><span>Nombre(s):</span><br></p>
                <%= @Acceso.Companero %>
                <p class="error"></p>
              </div>
              <div class="col-md-6">
                <p><span>Empresa:</span><br></p>
                <%= @Acceso.Empresa %>
                <p class="error"></p>
              </div>

            </div>
            <div>
              <br>
              <p><span>Mensaje:</span></p>
              <%= @Acceso.Mensaje %>
              <p class="error"></p>
            </div>
          </div>



        </div>
      </div>

    </section>
  </main>
</div>

app/views/accesos/showUser.html.erb
<header class="cabecera-principal">
  <div class="logo-princial">
    <%= image_tag 'logo.png', alt: 'Regerencia Data Center' %>
  </div>
  <div class="">

    <span><span><strong> Admin:</strong></span> <%= current_user.NombreCompleto %>.</span>
    <%= link_to "Cerrar session", logout_path, method: :delete, class: 'btn-custome btn-hollow-blue' %>

  </div>
</header>

<div class="cuerpo-principal">

  <aside class="menu">
    <div class="iconos estilo-menu ">
      <ul>
        <li class=""><a href="" class="hint--right" aria-label="Lista de solicitud"><span class="fa fa-address-book"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Crear Solicitud"><span class="fa fa-address-book"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Lista de acceso emergente"><span class="fa fa-ambulance"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Visitas"><span class="fa fa-clipboard"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Editar usuario"><span class="fa fa-edit"></span></a></li>
      </ul>
    </div>
    <div class="texto-iconos estilo-menu">
      <ul>
        <li class=""><%= link_to 'Lista de Solicitud', userInicio_path %></li>
        <li class=""><%= link_to 'Crear de Solicitud', new_solicitud_path %></li>
        <li class=""><%= link_to 'Lista de acceso emergente', accesosIndexUser_path %></li>
        <li class=""><a href="#"> Visitas</a></li>
        <li class=""><a href="#"> Editar usuario</a></li>
      </ul>
    </div>
  </aside>

  <main class="contenido-principal">
    <header class="contenido-titulo titulo-emergente">
      <h3 class="text-center"><span class="fa fa-ambulance"></span>Detalle acceso emergente</h3>
    </header>
    <section class=" contenido-user-crear " >
      <div class="cabecera-user-crear">
        <p><span>Id Solicitud:</span><%=@Acceso.id%></p>
        <p><span>Fecha:</span><%= @Acceso.created_at.strftime("%d/%B/%Y")   %></p>
      </div>




      <div class="datos-usuario">
        <h3>Datos del usuario</h3>
        <div>
          <div class="">
            <p><span>Usuario:</span> <%= @Acceso.Nombre %></p>
            <p><span>Codigo:</span> <%= @Acceso.CodigoEmpleado %></p>
            <p><span>Departamento:</span><%= @Acceso.Departamento %></p>


          </div>

          <div class="">
            <p><span>Correo:</span> <%= @Acceso.Correo %></p>
            <p><span>Función:</span> <%= @Acceso.Funcion %></p>
          </div>
        </div>
      </div>

      <div class="">
        <h3>Datos de la visita</h3>
        <div class="datos-vista">
          <div class="">

            <div class="row">
              <div class="col-md-6">
                <p><span>Nombre(s):</span><br></p>
                <%= @Acceso.Companero %>
                <p class="error"></p>
              </div>
              <div class="col-md-6">
                <p><span>Empresa:</span><br></p>
                <%= @Acceso.Empresa %>
                <p class="error"></p>
              </div>

            </div>
            <div>
              <br>
              <p><span>Mensaje:</span></p>
              <%= @Acceso.Mensaje %>
              <p class="error"></p>
            </div>
          </div>



        </div>
      </div>

    </section>
  </main>
</div>