config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#Rutas paera manipular las solicitudes
  #

get '/inicio' => 'solicitudes#index'
get '/solicitud/:id' => 'solicitudes#show',as: :verSolicitud
get '/new/solicitud'  => 'solicitudes#new'
post 'new/solicitud' =>'solicitudes#create'
get '/solicitud/:id' => 'solicitudes#show',as: :showSolicitud
get '/solicitud/admin/:id' => 'solicitudes#showAdmin',as: :showSolicitudAdmin
patch '/solicitud/admin/:id' =>'solicitudes#updateEstatus', as: :updateEstatus


#Rutas para manipular usuario
  # **************************
get '/users' => 'usuarios#index'
get '/new/usuario' => 'usuarios#new'
get '/usuario/:id/ver' => 'usuarios#ver', as: :showUser
post '/new/usuario' => 'usuarios#create'
get 'usuario/:id/edit' => 'usuarios#edit', as: :edit
patch 'usuario/:id' => 'usuarios#update', as: :update
get 'usuario/:id/show' => 'usuarios#editar', as: :editar_ver

  #Rutas para manipular session
  # ***************************
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
delete '/logout' => 'sessions#destroy'

#Rutas para manipularr Acceso Rapido
   get '/accesos' => 'accesos#index'
  get '/new/acceso' => 'accesos#new'
  post  '/new/acceso' =>'accesos#create'
get '/acceso/:id' => 'accesos#show', as: :showAcceso
  get '/accesos/user' => 'accesos#indexUser', as: :accesosIndexUser
  get '/acceso/user/:id' => 'accesos#showUser',as: :showAccesoUser



#Rutas para las solicitudes de los usuarios

get '/user/inicio' => 'solicitudes#indexUser',as: :userInicio



root 'sessions#new'

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :solicituds

  has_secure_password

 validates :Correo, presence: {message: 'No puede dejarse vacio'},uniqueness: {message:'Ya existe'},email: {message:'Inavlido, Utilizar @/gmail/hotmail/labreferencia/.com, ejemplo: example@labreferencia.com'}
 validates :CodigoEmpleado, presence: {message:'No puede dejarse vacio'}, uniqueness: {message:'Codigo ya existe'}
  validates :password, presence: {message:'No puede dejarse vacio'},length: {minimum: 8,maximum: 25,:message=>'El minimo de caracteres permitidos son 8'}
validates :Tipo,:Estatus,:Departamento,:Funcion,presence: {message:'No puede dejarse vacio'}

  def admin?
    self.Tipo=='Admin'
  end



end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def index
  @Usuario= Usuario.new

    @Usuarios = if params[:CodigoEmpleado]
                  Usuario.where('CodigoEmpleado LIKE ?', "%#{params[:CodigoEmpleado]}%")
                else

                  Usuario.paginate(:page => params[:page], :per_page => 8)
                end
  end

  def ver
    @Usuario = Usuario.find(params[:id])
  end

  def editar
    @usuario = Usuario.find(params[:id])
  end

  def new
    @Usuario =Usuario.new
    @Estatus=['Activo','Inactivo']
  end

  def create
    @Usuario =Usuario.new(params_user)
    if @Usuario.save
      redirect_to users_path, :notice => 'Usuario creado correctamente'
    else
      render 'new'
    end
  end

  def edit
    @Usuario=Usuario.find(params[:id])
    @Estatus=['Activo','Inactivo']

  end

  def update
    @Usuario=Usuario.find(params[:id])
    if @Usuario.update(params_user)
      redirect_to login_path,:notice => 'Usuario actualizado correctamente'
    else
      render 'edit'
    end
  end

  def delete
    @Usuario=Usuario.find(params[:id])
    if @Usuario.destroy
      redirect_to users_path, :notice => 'Usuario Eliminado correctamente'
    end
  end

  private

  def params_user
    params.require(:usuario).permit(:CodigoEmpleado,:NombreCompleto,:Departamento,:Funcion,:Usuario,:password,:Correo,:Estatus,:Tipo)
  end

end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/edit.html.erb
<h1 >EDITAR USUARIO</h1>
<%= form_for @Usuario, url: update_path(@Usuario) do |f|%>
  <% if @Usuario.errors.any? %>
    <div id="errorExplanation">
      <ul>
        <% @Usuario.errors.full_messages.each do |msg| %>
          <li  class="alert alert-danger" role="alert" ><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :CodigoEmpleado, :placeholder => 'Codigo de empleado'%>
  <%= f.text_field :NombreCompleto, :placeholder => 'Nombre Completo'%>
  <%= f.text_field :Departamento, :placeholder => 'Departamento'%>
  <%= f.text_field :Funcion, :placeholder => 'Funcion'%>
  <%= f.text_field :Usuario, :placeholder => 'Usuario'%>
  <%= f.password_field  :password, :placeholder => 'Contraseña'%>
  <%= f.text_field :Correo, :placeholder => 'Correo'%>
  <%= f.select :Estatus, ['Activo','Inactivo'],{ :prompt => "Seleccionar"}%>



  <%= f.submit 'Actualizar'%>





<%end%>

app/views/usuarios/index.html.erb
<header class="cabecera-principal">
  <div class="logo-princial">
    <%= image_tag 'logo.png', alt: 'Regerencia Data Center' %>
  </div>
  <div class="">
    <span><span><strong> Admin:</strong></span> <%=current_user.NombreCompleto %>.</span>
    <%= link_to "Cerrar session", logout_path, method: :delete, class: 'btn-custome btn-hollow-blue' %>
  </div>
</header>

<div class="cuerpo-principal">
  <aside class="menu">
    <div class="iconos estilo-menu">
      <ul>
        <li class=""><a href="inicio" class="hint--right" aria-label="Lista de solicitud"><span class="fa fa-address-book"></span></a></li>
        <li class=""><a href="accesos" class="hint--right" aria-label="Lista de acceso emergente"><span class="fa fa-ambulance"></span></a></li>
        <li class=""><a href="users" class="hint--right" aria-label="Usuario"><span class="fa fa-users"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Reportes"><span class="fa fa-file"></span></a></li>
        <li class=""><a href=""class="hint--right" aria-label="Estadisticas"><span class="fa fa-bar-chart-o"></span></a></li>
      </ul>
    </div>
    <div class="texto-iconos estilo-menu">
      <ul>
        <li class=""><%= link_to 'Lista de Solicitud', inicio_path %></li>
        <li class=""><%= link_to 'Lista de acceso emergente', accesos_path %></li>
        <li class=""><%= link_to 'Usuarios',users_path %></li>
        <li class=""><a href="#"> Reportes</a></li>
        <li class=""><a href="#"> Estadisticas</a></li>
      </ul>
    </div>
  </aside>

  <main class="contenido-principal contenido-informacion-usuarios">
    <header class="contenido-titulo titulo-usuarios">
      <h3 class="text-center"><span class="fa fa fa-users"></span>Usuarios</h3>
    </header>



    <section class="contenido-informacion contenido-informacion-usuarios">
      <div class="">
        <%= form_tag(users_path, method: :get) do %>
        <div class="manejar-usuarios">
          <div class="row">
         <div class="col-md-6">
           <%= text_field_tag :CodigoEmpleado,"",:placeholder=>'Buscar usuario',:class=>'form-control' %>
         </div>

            <div class="col-md-6">
          <button class="btn-custome btn-hollow-green" type="button" name="button" data-toggle="modal" data-target="#modalCrearUser">Crear Usuario</button>
            </div>

          </div>
        </div>
        <% end %>
        <table class="table-custome table-usuarios" summary="las solicitudes por usuario">
          <thead>
          <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Departamento</th>
            <th>Acción</th>
            <th></th>
          </tr>

          <thead>
          <tbody class="cuerpo-table">
          <% @Usuarios.each do |u| %>
          <tr >
            <td><%= u.CodigoEmpleado %></td>
            <td><%= u.NombreCompleto %></td>
            <td><%= u.Correo %></td>
            <td><%= u.Departamento %></td>
            <td><%= link_to 'Detalle',showUser_path(u)%></td>
            <td><button type="button" class="" data-toggle="modal" data-target="#modalEditarUser" name="button"><span class="fa fa-edit"></span><%= link_to 'Editar',edit_path(u)%></button></td>
          </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </section>

    <%if params[:CodigoEmpleado] %>

      <%else %>

    <footer class="controladores">
      <%= will_paginate @Usuarios, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </footer>

      <% end %>
  </main>
</div>



<!--Ventana modal detalle usuario-->
<div class="modal face modal-detalle-usuario" tabindex="-1" id="modalDetallesUsuario">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="">
          <button type="button" class=" times times-white close " data-dismiss="modal"><span class="fa fa-times"></span></button>
        </div>
        <header class="detalle-usuario">
          <p>Juan Ernesto Mota </p>
        </header>
        <div class="detalle-Info-usuario">
          <p>Código de empleado:<span>8542</span></p>
          <p>Correo:<span>juaneneresto123@gmail.com</span></p>
          <p>Departamento:<span>Tecnología</span></p>
          <p>Función:<span>Soporte</span></p>
          <p>Estatus:<span>Habilitado</span></p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ventana modal editar ususario -->
<div class="modal face modal-detalle-usuario modal-editar-usuario" tabindex="-1" id="modalEditarUser">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="">
          <button type="button" class="times times-white close" data-dismiss="modal"><span class="fa fa-times"></span></button>
        </div>
        <header class="detalle-usuario">
          <p>Editar usuario</p>
        </header>
        <form method="">
          <div class="detalle-Info-usuario editar-Info-usuario">
            <div class="">
              <div class="campo-editar-usuario">
                <label for="nombre-editar">Nombre:</label>
                <input type="text" id="nombre-editar" name="" value="Juan Ernesto Hernandéz">
              </div>
              <div class="campo-editar-usuario">
                <label for="codigo-editar">Código de empleado:</label>
                <input type="text" id="codigo-editar" name="" value="4548">
              </div>
              <div class="campo-editar-usuario">
                <label for="funcion-editar">Función:</label>
                <input type="text" id="funcion-editar" name="" value="Soporte">
              </div>
            </div>

            <div class="">
              <div class="campo-editar-usuario">
                <label for="corre-editar">Correo:</label>
                <input type="text" id="corre-editar" name="" value="juaneneresto123@gmail.com">
              </div>
              <div class="campo-editar-usuario">
                <label for="departamento-editar">Departamento:</label>
                <input type="text" id="departamento-editar" name="" value="Tecnología">
              </div>
              <div class=" estatus-editar-user campo-editar-usuario">
                <label for="#">Estatus:</label>
                <div class="">
                  <button type="button" class="btn-custome btn-hollow-green" name="button">Habilitado</button>
                  <button type="button" class="btn-custome btn-hollow-red" name="button">Deshabilitar</button>
                </div>
              </div>
            </div>
          </div>
          <div class="footer-btn-user">
            <button type="submit" class="btn-hollow-green btn-custome" name="button">Guardar cambio</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!--Ventana modal crear usuario-->
<div class="modal face modal-detalle-usuario modal-editar-usuario" tabindex="-1" id="modalCrearUser">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="">
          <button type="button" class="times times-white close" data-dismiss="modal"><span class="fa fa-times"></span></button>
        </div>
        <header class="detalle-usuario">
          <p>Crear usuario</p>
        </header>


        <%= form_for @Usuario, url: new_usuario_path(@Usuario)do |f| %>
          <% if @Usuario.errors.any? %>
            <div id="errorExplanation">
              <ul>
                <% @Usuario.errors.full_messages.each do |msg| %>
                  <li  class="alert alert-danger" role="alert" ><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>


          <div class="detalle-Info-usuario editar-Info-usuario">
            <div class="row">

            <div class="col-md-6">
              <div class="campo-editar-usuario">
                <label for="nombre-editar">Nombre:</label>
                <%= f.text_field :NombreCompleto, class: "form-registro", placeholder: "Nombre Completo" %>
              </div>
              <div class="campo-editar-usuario">
                <label for="codigo-editar">Código:</label>
                <%= f.text_field :CodigoEmpleado, class: "form-registro ", placeholder: "Codigo Empleado" %>
              </div>
              <div class="campo-editar-usuario">
                <label for="funcion-editar">Función:</label>
                <%= f.text_field :Funcion, class: "form-registro", placeholder: "Funcion" %>
              </div>
              <div class="campo-editar-usuario">
                <label for="departamento-editar">Estatus:</label>
                <%= f.select :Estatus, ['Activo', 'Inactivo'], {:prompt => "Seleccionar"} %>
              </div>
            </div>

            <div class="col-md-6">
              <div class="campo-editar-usuario">
                <label for="corre-editar">Correo:</label>
                <%= f.text_field :Correo, class: "form-registro", placeholder: "Correo" %>
              </div>
              <div class="campo-editar-usuario">
                <label for="departamento-editar">Departamento:</label>
                <%= f.text_field :Departamento, class: "form-registro", placeholder: "Departamento" %>
              </div>
              <div class="campo-editar-usuario">
                <label for="departamento-editar">Contrasena:</label>
                <%= f.password_field :password, class: "form-registro", placeholder: "Contraseña" %>
              </div>
              <div class="campo-editar-usuario">
                <label for="departamento-editar">Tipo:</label>
                <%= f.select :Tipo, ['Admin', 'User'], {:prompt => "Seleccionar"} %>
              </div>

            </div>
            </div>
          </div>



          <div class="footer-btn-user">
            <button type="submit" class="btn-hollow-green btn-custome" name="button">Guardar cambio</button>
          </div>
        <%end %>
      </div>
    </div>
  </div>
</div>

app/views/usuarios/new.html.erb
<%= form_for @Usuario, url: new_usuario_path(@Usuario)do |f| %>
  <% if @Usuario.errors.any? %>
    <div id="errorExplanation">
      <ul>
        <% @Usuario.errors.full_messages.each do |msg| %>
          <li  class="alert alert-danger" role="alert" ><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='container'>
    <div class='row'>

      <div class='col-md-6'>

        <%= f.text_field :CodigoEmpleado, class: "form-registro ", placeholder: "Codigo Empleado" %>


        <%= f.text_field :NombreCompleto, class: "form-registro", placeholder: "Nombre Completo" %>


        <%= f.text_field :Departamento, class: "form-registro", placeholder: "Departamento" %>


        <%= f.text_field :Funcion, class: "form-registro", placeholder: "Funcion" %>


        <%= f.text_field :Usuario, class: "form-registro", placeholder: "Usuario" %>
      </div>
      <div class='col-md-6'>
        <%= f.password_field :password, class: "form-registro", placeholder: "Contraseña" %>


        <%= f.text_field :Correo, class: "form-registro", placeholder: "Correo" %>


        <%= f.text_field :Tipo, class: "form-registro", placeholder: "Tipo" %>

        <%= f.select :Estatus, ['Activo','Inactivo'],{ :prompt => "Seleccionar"}%>


      </div>


      <%= f.submit class: "btn " %>

    </div>

  </div>

<% end %>

app/views/usuarios/ver.html.erb
<header class="cabecera-principal">
  <div class="logo-princial">
    <%= image_tag 'logo.png', alt: 'Regerencia Data Center' %>
  </div>
  <div class="">

    <span><span><strong> Admin:</strong></span> <%= current_user.NombreCompleto %>.</span>
    <%= link_to "Cerrar session", logout_path, method: :delete, class: 'btn-custome btn-hollow-blue' %>

  </div>
</header>
<div class="cuerpo-principal">
  <aside class="menu">
    <div class="iconos estilo-menu">
      <ul>
        <li class="">
          <a href="inicio" class="hint--right" aria-label="Lista de solicitud"><span class="fa fa-address-book"></span></a>
        </li>
        <li class="">
          <a href="accesos" class="hint--right" aria-label="Lista de acceso emergente"><span class="fa fa-ambulance"></span></a>
        </li>
        <li class="users"><a href="" class="hint--right" aria-label="Usuario"><span class="fa fa-users"></span></a></li>
        <li class=""><a href="" class="hint--right" aria-label="Reportes"><span class="fa fa-file"></span></a></li>
        <li class="">
          <a href="" class="hint--right" aria-label="Estadisticas"><span class="fa fa-bar-chart-o"></span></a></li>
      </ul>
    </div>
    <div class="texto-iconos estilo-menu">
      <ul>
        <li class=""><%= link_to 'Lista de Solicitud', inicio_path %></li>
        <li class=""><%= link_to 'Lista de acceso emergente', accesos_path %></li>
        <li class=""><%= link_to 'Usuarios', users_path %></li>
        <li class=""><a href="#"> Reportes</a></li>
        <li class=""><a href="#"> Estadisticas</a></li>
      </ul>
    </div>
  </aside>

  <main class="contenido-principal">
    <header class="contenido-titulo background-user">
      <h3 class="text-center"><span class="fa fa-address-book"></span>Detalle de la solicitud</h3>
    </header>
    <section class=" contenido-user-crear " >
      <div class="cabecera-user-crear">
        <p><span>Id Usuario:</span><%=@Usuario.id%></p>
        <p><span>Fecha de creacion:</span><%= @Usuario.created_at.strftime("%d/%B/%Y")   %></p>
      </div>




      <div class="datos-usuario">
        <h3>Datos del usuario</h3>
        <div>
          <div class="">
            <p><span>Usuario:</span> <%= @Usuario.NombreCompleto %></p>
            <p><span>Departamento:</span><%= @Usuario.Departamento %></p>
            <p><span>Estatus:</span> <%= @Usuario.Estatus %></p>
            <p><span>Tipo:</span> <%= @Usuario.Tipo %></p>


          </div>

          <div class="">
            <p><span>Usuario:</span> <%= @Usuario.Usuario %></p>
            <p><span>Codigo:</span> <%= @Usuario.CodigoEmpleado%></p>
            <p><span>Correo:</span> <%= @Usuario.Correo %></p>
            <p><span>Función:</span> <%= @Usuario.Funcion %></p>

          </div>
        </div>
      </div>



    </section>
  </main>
</div>